# Generated by Django 2.0.6 on 2018-06-17 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('source', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentationSubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.DocumentationGroup')),
            ],
        ),
        migrations.AddField(
            model_name='documentationentry',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.DocumentationGroup'),
        ),
    ]
