# Generated by Django 2.0.6 on 2018-06-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationgroup',
            name='pointsTo',
            field=models.CharField(default='learn', max_length=50),
        ),
    ]
