# Generated by Django 2.0.6 on 2018-07-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentationsubgroup',
            name='parent_group',
        ),
        migrations.RemoveField(
            model_name='documentationentry',
            name='group',
        ),
        migrations.AddField(
            model_name='documentationentry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='docs.DocumentationEntry'),
        ),
        migrations.DeleteModel(
            name='DocumentationGroup',
        ),
        migrations.DeleteModel(
            name='DocumentationSubGroup',
        ),
    ]
