# Generated by Django 2.0.6 on 2018-07-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20180701_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationentry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentationentry',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
