# Generated by Django 2.0.6 on 2018-07-02 17:53

import data_Insights_website.app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to=data_Insights_website.app.models.data_directory_path_with_uuid)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
