# Generated by Django 2.0.6 on 2018-07-01 19:05

import data_Insights_website.app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadeddata',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loadeddata',
            name='data',
            field=models.FileField(upload_to=data_Insights_website.app.models.data_directory_path_with_uuid),
        ),
    ]
