# Generated by Django 2.0.6 on 2018-07-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180701_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoadedData',
            new_name='DataFile',
        ),
    ]
